
package jdz.RTGen.dataType;

public enum Biome {
	OCEAN,

	TROPICAL_RAINFOREST, TROPICAL_SEASONAL_FOREST, THORN_FOREST, SAVANNAH, THORN_SCRUB, DESERT,

	TEMPERATE_RAINFOREST, TEMPERATE_FOREST, WOODLAND, GRASSLAND, SHRUBLAND,

	TAIGA, TUNDRA;
}
